services:
  - type: web
    name: digital-phonebook-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server-mongodb.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://adler0533_db_user:wq33331@cluster0.odnm3ka.mongodb.net/?appName=Cluster0
